{% set version = "3_0_20157_abdb1d1" %}
{% set buildid = "1020058" %}
{% set root = "pwiz_tools/Bumbershoot/" %}
{% set targets = root~"myrimatch//install "~root~"directag//install "~root~"tagrecon//install "~root~"idpicker//install "~root~"pepitome//install "~root~"quameter//install" %}

package:
  name: bumbershoot
  version: {{ version }}

source:
  url: http://teamcity.labkey.org/guestAuth/repository/download/ProteoWizard_BumbershootUpdateBioconda/{{ buildid }}:id/bumbershoot-src-without-t-{{ version }}.tar.bz2
  sha256: 9c69126aa4c812a495c74492b714797f6c71cc7438c73e256e2ae686f757cc96

build:
  number: 0
  script: bash -c "./quickbuild.sh -j{{ CPU_COUNT }} address-model=64 runtime-link=shared {{ targets }} && cp build-linux-x86_64/gcc-release-x86_64/* $PREFIX/bin"
  skip: True  # [osx]

requirements:
  build:
    - {{ compiler('cxx') }}
  run:

about:
  home: https://proteowizard.sourceforge.net
  license: Apache 2.0
  summary: The Bumbershoot tool suite for analyzing shotgun proteomic data

test:
  commands:
    - myrimatch --help
    - directag --help
    - quameter --help
    - pepitome --help
