{% set name = "anarci" %}
{% set version = "2020.04.23" %}
{% set commit = "19d9de50b2ab7ca80f4d2c45fd113139f4cad311" %}
{% set sha256 = "ccafdcf9ae9c6e319aa19270dfb3d6cfdd84281d697d8246114f0c9f249c7f0f" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://github.com/oxpig/ANARCI/archive/{{ commit }}.zip
  sha256: {{ sha256 }}

build:
  number: 0
  # noarch: python
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv"
  skip: True  # [win]

requirements:
  host:
    - python >=3.6
    - hmmmer >=3.1
  run:
    - hmmer >=3.1

test:
  imports:
    - anarci

about:
  home: http://opig.stats.ox.ac.uk/webapps/newsabdab/sabpred/anarci/
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: 'ANARCI: Antibody Numbering and Antigen Receptor ClassIfication'
